In [1]:
import sys
sys.path.append('..')
from itertools import permutations
from modified_sage_funcs import *
from imp_funcs import *

r, n = 2, 6
M = matroids.Uniform(r, n)
r = M.rank()
#S = (frozenset({0, 1, 2, 3}), frozenset({2, 3, 4, 5, 6}))
S = (frozenset({0}), frozenset({0}), frozenset({0}),
    frozenset({0, 1, 2}), frozenset({0, 1, 2, 3}))
k = len(S)
P = PolynomialRing(QQ, 'x', k)

In [2]:
def partitions(basis, weak_comp):
    """
    partitions a basis into weak components
    """
    parts = set()
    for perm in permutations(basis):
        partition = []
        start = 0
        for size in weak_comp:
            partition.append(frozenset(perm[start:start + size]))
            start += size
        parts.add(tuple(partition))
    return tuple(parts)

def base_partitions(bases, indexed_compositions):
    """
    partitions each basis into weak components
    """
    bases_partitions = {}
    for basis in bases:
        base_partitions = {}
        for i in indexed_compositions:
            base_partitions[i] = partitions(tuple(basis), indexed_compositions[i])
        bases_partitions[basis] = base_partitions
    return bases_partitions


In [3]:
def composition_weight(iwc, set_system, bp):
    """
    computes the weight of each composition
    """
    weights = {}
    for i in iwc:
        weight = 0
        for basis in bp:
            for basis_partition in bp[basis][i]:
                flag = True
                for x, y, z in zip(iwc[i], basis_partition, set_system):
                    if len(y.intersection(z)) == x:
                        continue
                    else:
                        flag = False
                        break
                if flag:
                    weight += 1
                    break
        weights[i] = weight
    return weights

In [4]:
def weighted_poly(M, set_system):
    d, n = M.full_rank(), len(M.groundset())
    k = len(set_system)
    P = PolynomialRing(QQ, 'x', k)
    bases = sorted([frozenset(sorted(X)) for X in bases_iterator(M)])
    indexed_compositions = {i : x for i, x in enumerate(weak_compositions(d, k))}
    bp = base_partitions(bases, indexed_compositions)
    weights = composition_weight(indexed_compositions, set_system, bp)
    def monomial(wc):
        return prod([P.gen(i)**wc[i] for i in range(len(wc))])
    def weighted_sum(weights):
        return sum([weights[i]*monomial(indexed_compositions[i]) for i in weights])
    return weighted_sum(weights)

In [5]:
def decompose(S):
    return tuple(frozenset([x]) for sets in S for x in sets)

indexed_compositions = {i : x for i, x in enumerate(weak_compositions(r, k))}

In [6]:
Sp = weighted_poly(M, S)
dSp = weighted_poly(M, decompose(S))

print(Sp)
# Ensure coefficients_dict is defined before using it
def coefficients_dict(f):
	return {f.exponents()[i]: f.coefficients()[i] for i in range(len(f.coefficients()))}

cdSp = coefficients_dict(dSp)
print(len(coefficients_dict(dSp)))
cdSp

2*x0*x3 + 2*x1*x3 + 2*x2*x3 + 3*x3^2 + 3*x0*x4 + 3*x1*x4 + 3*x2*x4 + 6*x3*x4 + 6*x4^2
33


{(1, 0, 0, 0, 1, 0, 0, 0, 0, 0): 1,
 (0, 1, 0, 0, 1, 0, 0, 0, 0, 0): 1,
 (0, 0, 1, 0, 1, 0, 0, 0, 0, 0): 1,
 (0, 0, 0, 1, 1, 0, 0, 0, 0, 0): 1,
 (1, 0, 0, 0, 0, 1, 0, 0, 0, 0): 1,
 (0, 1, 0, 0, 0, 1, 0, 0, 0, 0): 1,
 (0, 0, 1, 0, 0, 1, 0, 0, 0, 0): 1,
 (0, 0, 0, 1, 0, 1, 0, 0, 0, 0): 1,
 (0, 0, 0, 0, 1, 1, 0, 0, 0, 0): 1,
 (0, 0, 0, 0, 1, 0, 1, 0, 0, 0): 1,
 (0, 0, 0, 0, 0, 1, 1, 0, 0, 0): 1,
 (1, 0, 0, 0, 0, 0, 0, 1, 0, 0): 1,
 (0, 1, 0, 0, 0, 0, 0, 1, 0, 0): 1,
 (0, 0, 1, 0, 0, 0, 0, 1, 0, 0): 1,
 (0, 0, 0, 1, 0, 0, 0, 1, 0, 0): 1,
 (0, 0, 0, 0, 0, 1, 0, 1, 0, 0): 1,
 (0, 0, 0, 0, 0, 0, 1, 1, 0, 0): 1,
 (1, 0, 0, 0, 0, 0, 0, 0, 1, 0): 1,
 (0, 1, 0, 0, 0, 0, 0, 0, 1, 0): 1,
 (0, 0, 1, 0, 0, 0, 0, 0, 1, 0): 1,
 (0, 0, 0, 1, 0, 0, 0, 0, 1, 0): 1,
 (0, 0, 0, 0, 1, 0, 0, 0, 1, 0): 1,
 (0, 0, 0, 0, 0, 0, 1, 0, 1, 0): 1,
 (0, 0, 0, 0, 0, 0, 0, 1, 1, 0): 1,
 (1, 0, 0, 0, 0, 0, 0, 0, 0, 1): 1,
 (0, 1, 0, 0, 0, 0, 0, 0, 0, 1): 1,
 (0, 0, 1, 0, 0, 0, 0, 0, 0, 1): 1,
 (0, 0, 0, 1, 0, 0, 0, 0, 0,

In [7]:
def specialize(f, S1, S2):
    P1 = PolynomialRing(QQ, 'x', len(S1))
    P2 = PolynomialRing(QQ, 'x', len(S2))
    k = 0
    for i, x in enumerate(S1):
        subs_dict = {P2.gen(k + j): P1.gen(i) for j in range(len(x))}
        f = f.subs(subs_dict)
        k += len(x)
    return f

dSp1 = specialize(dSp, S, decompose(S))

In [8]:
def coefficients_dict(f):
    return {f.exponents()[i]: f.coefficients()[i] for i in range(len(f.coefficients()))}

coefficients_dict(dSp1)

{(1, 0, 0, 1, 0, 0, 0, 0, 0, 0): 2,
 (0, 1, 0, 1, 0, 0, 0, 0, 0, 0): 2,
 (0, 0, 1, 1, 0, 0, 0, 0, 0, 0): 2,
 (0, 0, 0, 2, 0, 0, 0, 0, 0, 0): 3,
 (1, 0, 0, 0, 1, 0, 0, 0, 0, 0): 3,
 (0, 1, 0, 0, 1, 0, 0, 0, 0, 0): 3,
 (0, 0, 1, 0, 1, 0, 0, 0, 0, 0): 3,
 (0, 0, 0, 1, 1, 0, 0, 0, 0, 0): 9,
 (0, 0, 0, 0, 2, 0, 0, 0, 0, 0): 6}

In [9]:
print(Sp)
coefficients_dict(Sp)

2*x0*x3 + 2*x1*x3 + 2*x2*x3 + 3*x3^2 + 3*x0*x4 + 3*x1*x4 + 3*x2*x4 + 6*x3*x4 + 6*x4^2


{(1, 0, 0, 1, 0): 2,
 (0, 1, 0, 1, 0): 2,
 (0, 0, 1, 1, 0): 2,
 (0, 0, 0, 2, 0): 3,
 (1, 0, 0, 0, 1): 3,
 (0, 1, 0, 0, 1): 3,
 (0, 0, 1, 0, 1): 3,
 (0, 0, 0, 1, 1): 6,
 (0, 0, 0, 0, 2): 6}

In [10]:
def normalize(f):
    return sum(f.monomials()[i] * f.coefficients()[i]/prod([factorial(x) for x in f.exponents()[i]]) for i in range(len(f.coefficients())))

In [11]:
print(normalize(Sp).is_lorentzian())        # normalized weighted polynomial of S
print(normalize(dSp).is_lorentzian())       # normalized weighted polynomial of decompose(S)
print(normalize(dSp1).is_lorentzian())      # normalized weighted polynomial of decompose(S)
print(P(normalize(dSp1 - Sp)).is_lorentzian()) # normalized difference of the two polynomials

True
True
True
True


In [12]:
import numpy as np
from collections import defaultdict

def get_first_duplicate_p_matrix(S):
  """
  Identifies the first duplicate set in a sequence S and computes the
  transformation matrix P for lifting it.

  A "duplicate set" T is defined as a set that appears at least twice
  in the sequence S and has size |T| >= 2. The "first" duplicate set
  is the one whose first appearance in S has the minimum index among all
  duplicate sets.

  Args:
    S: A list or tuple of sets (or other iterable collections). Elements
       within the sets should be hashable.

  Returns:
    A tuple (P, T, dup_indices) where:
      - P: The (lk + n - l) x n transformation matrix as a NumPy array.
      - T: The first duplicate set found (as a frozenset).
      - dup_indices: A sorted list of the indices in S where T appears.
    Returns None if no duplicate set (with size >= 2) is found in S.
  """
  n = len(S)
  if n == 0:
    return None

  set_counts_indices = defaultdict(list)
  # Use frozenset for hashing
  frozen_S = [frozenset(item) for item in S]

  # Record indices for each unique frozenset
  for i, fset in enumerate(frozen_S):
    set_counts_indices[fset].append(i)

  first_dup_set = None
  dup_indices = []
  min_first_index = n # Initialize higher than any possible index

  # Find the first duplicate set
  for fset, indices in set_counts_indices.items():
    # Check conditions: |T| >= 2 and appears >= 2 times
    if len(fset) >= 2 and len(indices) >= 2:
      first_index = indices[0]
      if first_index < min_first_index:
        min_first_index = first_index
        first_dup_set = fset
        # Keep indices sorted for consistent row mapping later
        dup_indices = sorted(indices)

  # If no duplicate set was found
  if first_dup_set is None:
    return None

  T = first_dup_set
  l = len(dup_indices) # Number of times T appears
  k = len(T)           # Size of T
  t_elements = sorted(list(T)) # Consistent order for elements

  # Calculate dimensions for P and lifted sequence
  n_tilde = l * k + (n - l)

  # Initialize P matrix
  P = np.zeros((n_tilde, n), dtype=int) # Integer entries

  # Get indices of the sets that are *not* the chosen duplicate T
  other_indices = sorted([i for i in range(n) if i not in dup_indices])

  # --- Construct P ---
  # Map original indices to row indices in P

  # Rows 0 to lk-1 correspond to the l*k singletons
  # Map duplicate index to its position (0 to l-1) among duplicates
  dup_idx_to_pos = {idx: i for i, idx in enumerate(dup_indices)}

  # Rows lk to n_tilde-1 correspond to the other sets
  # Map other index to its row position (lk to n_tilde-1)
  other_idx_to_row = {idx: l*k + i for i, idx in enumerate(other_indices)}

  # Fill columns of P
  for c in range(n): # Iterate through columns (original indices 0 to n-1)
    if c in dup_indices:
      # This column corresponds to a duplicate set T
      pos = dup_idx_to_pos[c] # Which copy of T is this (0 to l-1)
      start_row = pos * k
      end_row = start_row + k
      # Set the block of k rows corresponding to this T's singletons to 1
      P[start_row:end_row, c] = 1
    else:
      # This column corresponds to a non-duplicate set
      row = other_idx_to_row[c]
      # Set the single corresponding row to 1
      P[row, c] = 1

  return P, T, dup_indices

# --- Example Usage ---
# Example from the document [cite: 102] (adjusted slightly for set notation)
S_example = S
result = get_first_duplicate_p_matrix(S_example)

if result:
  P_matrix, T_set, indices = result
  print("Input S:", S_example)
  print("-" * 20)
  print("First duplicate set T:", set(T_set)) # Display as regular set
  print("Indices of T in S:", indices)
  print("Resulting P matrix:")
  print(P_matrix)
else:
  print("Input S:", S_example)
  print("No duplicate set (size >= 2) found.")

print("\n" + "=" * 30 + "\n")

# Example with no duplicates >= size 2
S_no_dup = [{1}, {1}, {2}, {3}, {4, 5}]
result_no_dup = get_first_duplicate_p_matrix(S_no_dup)

if result_no_dup:
    P_matrix, T_set, indices = result_no_dup
    print("Input S:", S_no_dup)
    print("-" * 20)
    print("First duplicate set T:", set(T_set))
    print("Indices of T in S:", indices)
    print("Resulting P matrix:")
    print(P_matrix)
else:
    print("Input S:", S_no_dup)
    print("No duplicate set (size >= 2) found.")

print("\n" + "=" * 30 + "\n")

# Example where first duplicate appears later
S_later_dup = [{1}, {2}, {3, 4}, {5}, {3, 4}]
result_later_dup = get_first_duplicate_p_matrix(S_later_dup)

if result_later_dup:
    P_matrix, T_set, indices = result_later_dup
    print("Input S:", S_later_dup)
    print("-" * 20)
    print("First duplicate set T:", set(T_set))
    print("Indices of T in S:", indices)
    print("Resulting P matrix:")
    print(P_matrix)
else:
    print("Input S:", S_later_dup)
    print("No duplicate set (size >= 2) found.")

Input S: (frozenset({0}), frozenset({0}), frozenset({0}), frozenset({0, 1, 2}), frozenset({0, 1, 2, 3}))
No duplicate set (size >= 2) found.


Input S: [{1}, {1}, {2}, {3}, {4, 5}]
No duplicate set (size >= 2) found.


Input S: [{1}, {2}, {3, 4}, {5}, {3, 4}]
--------------------
First duplicate set T: {3, 4}
Indices of T in S: [2, 4]
Resulting P matrix:
[[0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]]


In [13]:
def get_A_matrix(S, bases):
    """
    Calculates the coefficient matrix A(S) for a rank 2 matroid.

    The matrix A(S) is an n x n symmetric matrix where n = len(S).
    - A[i, i] = c_ii(S) = number of bases B such that B is a subset of S_i.
    - A[i, j] = c_ij(S) = number of bases B = {b1, b2} such that
                        (b1 in S_i and b2 in S_j) or (b1 in S_j and b2 in S_i).
                        This corresponds to the coefficient of x_i * x_j in the
                        (denormalized) based cover class polynomial.

    Args:
    S: A list or tuple of sets (or other iterable collections), representing
        the sequence (S_1, ..., S_n). Elements within the sets should be
        hashable.
    bases: An iterable collection of sets or frozensets, where each inner
            set represents a base B of the rank 2 matroid M. All bases B
            must have |B| = 2.

    Returns:
    A NumPy array representing the n x n symmetric matrix A(S).
    Returns None if bases are not all of size 2.
    """
    n = len(S)
    if n == 0:
        return np.zeros((0, 0), dtype=int)

    # Convert S_i to sets for efficient lookup
    S_sets = [set(s_i) for s_i in S]

    # Initialize A matrix
    A = np.zeros((n, n), dtype=int)

    # Check if bases are valid (all size 2) and convert to frozensets
    processed_bases = []
    for B in bases:
        if len(B) != 2:
            print(f"Error: Base {B} does not have size 2. Matroid must be rank 2.")
            return None
        processed_bases.append(frozenset(B))

    # Iterate through each base B in the matroid M
    for B in processed_bases:
        b1, b2 = tuple(B) # Get the two elements of the base

        # Calculate diagonal entries A[i, i] = c_ii(S)
        for i in range(n):
            # Check if B is a subset of S_i
            if B.issubset(S_sets[i]):
                A[i, i] += 1

        # Calculate off-diagonal entries A[i, j] = c_ij(S) for i < j
        for i in range(n):
            for j in range(i + 1, n):
                # Check if one element is in S_i and the other is in S_j
                if (b1 in S_sets[i] and b2 in S_sets[j]) or \
                (b1 in S_sets[j] and b2 in S_sets[i]):
                    A[i, j] += 1
                    A[j, i] += 1 # Maintain symmetry

    return A

bases = list(bases_iterator(M))

A = get_A_matrix(S, bases)

print("Bases:", bases)
print("-" * 20)
print("Input S:", S)
print("-" * 20)
print("Calculated A(S) matrix:")
print(A)

Bases: [frozenset({0, 1}), frozenset({0, 2}), frozenset({0, 3}), frozenset({0, 4}), frozenset({0, 5}), frozenset({1, 2}), frozenset({1, 3}), frozenset({1, 4}), frozenset({1, 5}), frozenset({2, 3}), frozenset({2, 4}), frozenset({2, 5}), frozenset({3, 4}), frozenset({3, 5}), frozenset({4, 5})]
--------------------
Input S: (frozenset({0}), frozenset({0}), frozenset({0}), frozenset({0, 1, 2}), frozenset({0, 1, 2, 3}))
--------------------
Calculated A(S) matrix:
[[0 0 0 2 3]
 [0 0 0 2 3]
 [0 0 0 2 3]
 [2 2 2 3 6]
 [3 3 3 6 6]]


In [14]:
"""
S = (frozenset({0}), frozenset({1}), frozenset({0, 2}),
    frozenset({0, 2}), frozenset({3}))
"""
dS = (frozenset({0}), frozenset({0}), frozenset({2}),
    frozenset({2}), frozenset({1}), frozenset({3}))
ASp = get_A_matrix(dS, bases)
ASp

array([[0, 0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1],
       [1, 1, 0, 0, 1, 1],
       [1, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1, 0]])

In [15]:
result = get_first_duplicate_p_matrix(S)
P = Matrix([[1, 0, 0, 0],
            [0, 1, 0, 0],
            [1, 0, 0, 0],
            [0, 1, 0, 0],
            [0, 0, 1, 0],
            [0, 0, 0, 1]])
P

[1 0 0 0]
[0 1 0 0]
[1 0 0 0]
[0 1 0 0]
[0 0 1 0]
[0 0 0 1]

In [16]:
Q  = P.transpose() @ ASp
R = Q @ P
R

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 0, 1],
       [2, 2, 1, 0]])

In [17]:
R-A

ValueError: operands could not be broadcast together with shapes (4,4) (5,5) 