In [6]:
import numpy as np

M = np.array([
    [3, 1, 0, 2, 1],
    [1, 4, 2, 0, 1],
    [0, 2, 5, 1, 0],
    [2, 0, 1, 3, 2],
    [1, 1, 0, 2, 4]
])

def get_minor_determinant_matrix(M):
    """
    Compute matrix H where h_{ij} = m_{ii} * m_{jj} - m_{ij} * m_{ji}
    
    Args:
        M: Input matrix (n x n)
    
    Returns:
        Matrix H of size n x n where h_{ij} = m_{ii} * m_{jj} - m_{ij} * m_{ji}
    """
    n, m = M.shape
    
    if n != m:
        raise ValueError("Matrix must be square")
    
    # Initialize result matrix
    H = np.zeros((n, n), dtype=np.int64)
    
    # Compute each entry h_{ij} = m_{ii} * m_{jj} - m_{ij} * m_{ji}
    for i in range(n):
        for j in range(n):
            H[i, j] = M[i, i] * M[j, j] - M[i, j] * M[j, i]
    
    return H

print("Original Matrix M:")
print(M)
print()

get_minor_determinant_matrix(M)


Original Matrix M:
[[3 1 0 2 1]
 [1 4 2 0 1]
 [0 2 5 1 0]
 [2 0 1 3 2]
 [1 1 0 2 4]]



array([[ 0, 11, 15,  5, 11],
       [11,  0, 16, 12, 15],
       [15, 16,  0, 14, 20],
       [ 5, 12, 14,  0,  8],
       [11, 15, 20,  8,  0]])